In [1]:
import pandas as pd

quation 1:
there are many types function in pandas 
function are
1)head()
2)tail()
3)groupby()
4)reindex()
5)plot()
6)apply()
7)applymap()
8)sort_value

In [5]:
df2=pd.read_csv("services.csv")

In [6]:
df2.head()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN

In [7]:
df2.tail()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [16]:
df2.reindex(["a",'b','c','d','e','f','g','h'])

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
c,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
e,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
f,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
g,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
h,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df3=df2.groupby("location_id")

In [29]:
df2["new_column"]=df2["location_id"].apply(lambda x:x**2)

In [32]:
df2.sort_values("location_id",ascending=False)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids,new_column
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN,484
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05",484
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN,441
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN,400
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN,361
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN,324
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN,289
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN,256
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN,225
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN,196
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN,169
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN,144
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN,121
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN,100
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN,81
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN,64
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN,49
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,NaN,...,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN,36
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN,25
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN,16
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN,9
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN,4
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN,1

quation 2:

In [37]:

df3=pd.DataFrame({"a":[1,2,3,4,5],"b":[4,5,7,8,9],"c":[9,6,7,2,5]})
df3.reindex([1,2,3,4])

   a  b  c
1  2  5  6
2  3  7  7
3  4  8  2
4  5  9  5

quation 3:

In [38]:
df=pd.DataFrame({"values":[10, 20, 30, 40, 50]})

In [41]:
df["values"][0:3].sum()

60

quation 4:

In [55]:
df=pd.DataFrame({"text":["PW Skills is your one-stop-shop for upscaling. Get maximum value for timeand resources you invest, with job-ready courses & high-technology,available at the lowest cost."]})
df["word_count"]=df["text"].apply(len)

In [56]:
df

                                                text  word_count
0  PW Skills is your one-stop-shop for upscaling....         169

quation 5:

TypeError: 'tuple' object is not callable

quation 6

pd.read_excel() funtion is used for read excel file

quation 7:

In [12]:
df3=pd.DataFrame({'Email':["john.doe@example.com"]})
df3["user_name"]=df3["Email"].str.split('@').str.get(0)

In [13]:
df3

                  Email user_name
0  john.doe@example.com  john.doe

quation 8:

In [14]:
 df=pd.DataFrame({'a':[3,8,6,2,9],'b':[5,2,9,3,1],'c':[1,7,4,5,2]})

In [43]:
def data(df):
    filter_data=(df['a']>5)&(df['b']<10)
    return filter_data

In [48]:
row=df[data(df)]

In [49]:
print(row)

   a  b  c  new_file
1  8  2  7      True
2  6  9  4      True
4  9  1  2      True

quation 9:

In [50]:
df=pd.DataFrame({"values":[4,1,2,8,7,9,6,6]})

In [51]:
def descibe(df):
    print(df["values"].mean())
    print(df["values"].median())
    print(df["values"].std())
    return

In [52]:
descibe(df)

5.375
6.0
2.8252686345094435

quation 10:

In [56]:
dict={"sale":[10,12,14,18,19,20,25],"date":["2023-01-01","2023-01-02","2023-01-03","2023-01-04","2023-01-05","2023-01-06",'2023-01-07']}

In [67]:
df2=pd.DataFrame(dict)
df2

   sale        date
0    10  2023-01-01
1    12  2023-01-02
2    14  2023-01-03
3    18  2023-01-04
4    19  2023-01-05
5    20  2023-01-06
6    25  2023-01-07

In [75]:

df2["movies_avrage"]=df["sale"].rolling(window=7).mean()

KeyError: 'sale'

quation 12:

In [2]:
df=pd.date_range(start="2023-01-01",end="2023-01-31")

In [3]:
df

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31'],
              dtype='datetime64[ns]', freq='D')

quation 13: